### PR TITLE
created basic print with api functionality

### PR DESCRIPTION
**Pull request by matts-dev**
There are merge conflicts to resolve before this should be merged.

### CODE REVIEW

**Comment by matts-dev** [comment]
Okay, conflicts are resolved. I think we can merge this before we have finished working on adding to the constructor stuff.

**Review by andersonmc2 — CHANGES_REQUESTED** [review]
This isn't compiling for me, might have something to do with the bracket on Matrix.java line 259

**Comment by matts-dev** [comment]
Had to fix a conflict on github's page, probably left a braket somewhere. I'll take a look.

**Review by matts-dev — COMMENTED** [review]
I think I fixed it, didn't see your suggestions.

**Review by andersonmc2 — APPROVED** [review]

**Pull request merged**
