### PR TITLE
hotfix to get arrayLeftDividEquals and arrayLeftDivide checkstyle compliant and compiling. :)

### PR DESCRIPTION
**Pull request by matts-dev**
I pulled the code and got it compiling on my IDE, didn't test makefile yet.

### CODE REVIEW

**Comment by matts-dev** [comment]
makefile seems to work. 👍

**Comment by halvorsenca** [comment]
sorry about that I meant to make a branch and then push from that so we could merge later and forgot to to do it so I pushed it and it caused to where I could do a pull request I apologize for that

**Review by halvorsenca — APPROVED** [review]
everything looks good to me in terms of the changes, once again I apologize for sucking.

**Comment by matts-dev** [comment]
Lol, you're good.

**Pull request merged**
